source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'pg'
gem 'thin'
gem 'shotgun'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'dry-initializer'
gem 'curb', '= 0.9.7'
gem 'transmission-rpc-ruby'
gem 'redis'
gem 'sidekiq'
gem 'sidekiq-unique-jobs'
gem 'sidekiq-cron'
gem 'aasm'
gem 'omniauth-google-oauth2'
gem 'google-api-client'

group :development, :test do
  gem 'dotenv'
  gem 'rubocop'
  gem 'rubocop-rspec'
  gem 'rubocop-performance'
end

group :test do
  gem 'rspec'
  gem 'rspec-sidekiq'
  gem 'rspec_junit_formatter'
  gem 'factory_bot'
  gem 'faker'
  gem 'simplecov'
  gem 'database_cleaner'
  gem 'webmock'
  gem 'capybara'
end
