default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV.fetch('DATABASE_URL', '') %>
  pool: <%= ENV.fetch('DATABASE_POOL') { 25 } %>
  timeout: 5000

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
